### ISSUE TITLE
Windows system variables

### ISSUE THREAD

**Issue by vbourgeois** [strongloop/loopback-connector-oracle#19]
Hello,

When I installed the project, "instantclient\vc11" and "instantclient" directories were automatically added to the User variable PATH. When I tried to execute "example/app.js", I had the following error:

$ node example/app.js

D:\userfiles\vincent.bourgeois\Documents\loopback-connector-oracle\lib\oracle.js:11
    throw err;
          ^
Error: The specified procedure could not be found.
D:\userfiles\vincent.bourgeois\Documents\loopback-connector-oracle\node_modules\strong-oracle\build\Release\oracle_bindings.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\userfiles\vincent.bourgeois\Documents\loopback-connector-oracle\node_modules\strong-oracle\lib\oracle.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I had to add the 2 directories to the System variable Path manually for the example to work.
I don't know if you can automate it, but it took me some time to find the issue, so maybe it could be helpful if you add this to the doc.

Thanks.

**Comment by dhmlau** [comment]
@vbourgeois, do you still have this problem?  Can I close it?  Thanks.
