### ISSUE TITLE
Fix CI failure observed in loopback-datasource-juggler

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-oracle#96]
as a dependant of loopback-datasource-juggler, oracle fails in juggler pr's CI tests:
```
/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/oracledb/lib/oracledb.js:37
    throw err;
    ^

Error: libaio.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/oracledb/lib/oracledb.js:32:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/oracledb/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/lib/oracle.js:12:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/index.js:9:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at global.getDataSource.global.getSchema (/home/jenkins/workspace/ds/loopback-connector-oracle~master/test/init/init.js:18:23)
    at Suite.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/loopback-datasource-juggler/test/manipulation.test.js:878:8)
    at context.describe.context.context (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/loopback-datasource-juggler/test/manipulation.test.js:16:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/loopback-datasource-juggler/test/common.batch.js:10:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/test/oracle.test.js:10:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/jenkins/workspace/ds/loopback-connector-oracle~master/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
npm ERR! Test failed.  See above for more details.
```
CI link: https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-oracle~master/211/console

**Comment by jannyHou** [comment]
@ritch PTAL. Thanks

**Comment by jannyHou** [comment]
Close it in favour of https://github.com/strongloop-internal/scrum-loopback/issues/1258
